# Static Prompt: It is a research tool that allows users to input a research query and receive a summarized 
# response using the Google Generative AI model. The tool is built using Streamlit for the user interface and
#  the langchain_google_genai library to interact with the Google Generative AI model. 
# The API key for accessing the model is loaded from an environment variable using the dotenv library.


# from langchain_google_genai import ChatGoogleGenerativeAI
# from dotenv import load_dotenv
# import os
# import streamlit as st

# load_dotenv()

# model = ChatGoogleGenerativeAI(
#     model="gemini-3.5-flash",
#     google_api_key=os.getenv("GOOGLE_API_KEY")
# )
# st.header('Research Tool')

# user_input = st.text_input("Enter your research query:")

# if st.button('Summarize'):
#     result = model.invoke(user_input)
#     st.write(result.content)






# Dynamic Prompt: In addition to the research query input, the tool also allows users to select a research paper
#  from a predefined list, choose an explanation style (beginner-friendly, technical, code-oriented, or 
# mathematical), and specify the desired length of the explanation (short, medium, or long). These additional 
# inputs can be used to further customize the response generated by the Google Generative AI model based on the
#  user's preferences.
from langchain_google_genai import ChatGoogleGenerativeAI
from dotenv import load_dotenv
import os
import streamlit as st
from langchain_core.prompts import PromptTemplate, load_prompt

load_dotenv()

model = ChatGoogleGenerativeAI(
    model="gemini-2.5-flash",
    google_api_key=os.getenv("GOOGLE_API_KEY")
)
st.header('Research Tool')

paper_input = st.selectbox( "Select Research Paper Name", ["Attention Is All You Need", "BERT: Pre-training of Deep Bidirectional Transformers", "GPT-3: Language Models are Few-Shot Learners", "Diffusion Models Beat GANs on Image Synthesis"] )

style_input = st.selectbox( "Select Explanation Style", ["Beginner-Friendly", "Technical", "Code-Oriented", "Mathematical"] ) 

length_input = st.selectbox( "Select Explanation Length", ["Short (1-2 paragraphs)", "Medium (3-5 paragraphs)", "Long (detailed explanation)"] )

template = load_prompt("template.json")



if st.button('Summarize'):
    chain = template | model
    result = chain.invoke({
    "paper_input": paper_input,
    "style_input": style_input,
    "length_input": length_input
    })
    st.write(result.content)
